### PR TITLE
add dark mode styles

### LINKED ISSUE #5: Feature: add "Dark Mode"
Add a "Dark Mode".

Feature request by Daniel Rey López.

### PR DESCRIPTION
**Pull request by iam-robin**
Fixes #5 

- added dark mode styles for the new tab page
- triggered when the local system is using a dark mode appearance

Tested the extension with the new feature locally with light and dark mode system setting.

### CODE REVIEW

**Comment by rollecode** [comment]
@iam-robin @folletto  I have tested this and it works if you have dark mode enabled system-wide. Any way to set it up anyway by some simple setting? Or is the mentality of this extension to not have any settings at all? On Windows I'm using dark mode but on macOS I actually like the light mode on Finder and OS and choose the dark mode for apps individually.

**Comment by folletto** [comment]
Hi! I'm not sure why I didn't get the notification for this, massive apologies. I'll have a look as soon as I've a free moment.

**Comment by rollecode** [comment]
@folletto No worries! Just found out about this yesterday. Good work job so far, I like the minimalism.

The colors in this PR:

Screen-Shot-2022-01-05-09-35-16 21

However I prefer even more darker. Modified a bit to achieve GitHub-like dark look:

Screen-Shot-2022-01-05-09-51-56 27

CSS:
```css
body {
  background-color: rgb(13, 17, 23);
}

.bookmark > a:hover {
  background-color: rgb(22, 27, 34);
}

.bookmark__label {
  color: rgb(201, 209, 217)
}

.motivational {
  color: rgb(48, 54, 61);
}
```

Just a thought. What do you think?

**Comment by folletto** [comment]
I gave it a try with the two color combinations. 
I feel that given the other parts of Chrome are dark gray, as well as macOS general UI, and specifically the URL background is #202124 I feel matching it achieves a better color balance — similar on how the light color isn't too light either.

**Comment by folletto** [comment]
Thank you for your contribution, this has now been submitted to the Chrome store as version 1.1.0, waiting for review.

**Comment by iam-robin** [comment]
I just saw by chance that my new tab is displayed in the dark design. Was very pleased! Thanks for merging my contribution.

**Comment by folletto** [comment]
Thanks to you! :)

**Pull request merged**
